# Generated by Django 5.1.6 on 2025-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_chapter_description_alter_manga_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
