# Generated by Django 5.1.6 on 2025-02-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_chapter_description_alter_manga_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.volume'),
        ),
    ]
