# Generated by Django 5.1.6 on 2025-02-08 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_chapter_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
            ],
        ),
        migrations.RemoveField(
            model_name='volume',
            name='manga',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Manga',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
