# Generated by Django 5.1.6 on 2025-02-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_api_remove_volume_manga_delete_chapter_delete_manga_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name': 'API', 'verbose_name_plural': 'APIs'},
        ),
        migrations.AddConstraint(
            model_name='api',
            constraint=models.UniqueConstraint(fields=('ip', 'port'), name='unique_ip_port'),
        ),
    ]
