# Generated by Django 4.2.19 on 2025-02-08 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_api_options_api_unique_ip_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='timeout',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
    ]
