# Generated by Django 4.2.19 on 2025-02-10 11:32

import database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_api_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='ip',
            field=database.models.IPOrHostnameField(),
        ),
    ]
